import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'README',
    {
      type: 'category',
      label: 'Background',
      items: [
        {
          type: 'doc',
          id: 'ABOUT_FIRST',
        },
        {
          type: 'doc',
          id: 'WHO_WE_ARE',
        },
        {
          type: 'doc',
          id: 'TEAM_ORGANIZATION',
        },
      ],
    },
    {
      type: 'category',
      label: 'Team Operations',
      items: [
        {
          type: 'doc',
          id: 'SAFETY_CULTURE',
        },
        {
          type: 'doc',
          id: 'DECISION_MAKING',
        },
        {
          type: 'doc',
          id: 'CONCERN_RESOLUTION',
        },
        {
          type: 'doc',
          id: 'MEETING_STANDARDS',
        },
        {
          type: 'doc',
          id: 'WORKSPACE',
        },
        {
          type: 'doc',
          id: 'SEASON_SCHEDULE',
        },
      ],
    },
    {
      type: 'category',
      label: 'Attendance and Behavior',
      items: [
        {
          type: 'doc',
          id: 'BEHAVIOR_STANDARDS',
        },
        {
          type: 'doc',
          id: 'DRESS_CODE',
        },
        {
          type: 'doc',
          id: 'VARSITY_STANDARDS',
        },
        {
          type: 'doc',
          id: 'ATTENDANCE_STANDARDS',
        }
      ],
    },
    {
      type: 'category',
      label: 'Robot Standards',
      items: [
        {
          type: 'doc',
          id: 'COMPETITION_READY',
        },
        {
          type: 'doc',
          id: 'TIBS',
        },
        {
          type: 'doc',
          id: 'VARSITY_STANDARDS',
        },
        {
          type: 'doc',
          id: 'ATTENDANCE_STANDARDS',
        }
      ],
    },
    {
      type: 'category',
      label: 'Workspace Standards',
      items: [
        {
          type: 'doc',
          id: 'CLEANLINESS_STANDARDS',
        },
        {
          type: 'doc',
          id: 'INJURIES',
        }
      ],
    },
  ],
};

export default sidebars;
